### ISSUE TITLE
Add https://github.com/lawrencegripper/azbrowse

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/hd-home#92]
See also https://github.com/LinuxSuRen/hd-home/issues/63#issuecomment-937875301

An example https://github.com/LinuxSuRen/hd-home/pull/56

**Comment by nishant-giri** [comment]
@LinuxSuRen, could you kindly assign me this task?

**Comment by bindu-r02** [comment]
@LinuxSuRen - Submitted pull request #94 for issue #94
